"""
Shared language utilities for Yukti AI.
Provides centralised mapping of language codes to human‑readable names,
and helper functions for normalising language codes.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

# ----------------------------------------------------------------------
# Language Name Mapping (ISO 639-1 codes to full names)
# ----------------------------------------------------------------------
LANGUAGE_NAMES = {
    # Indian languages
    'hi': 'Hindi',
    'en': 'English',
    'ur': 'Urdu',
    'bn': 'Bengali',
    'te': 'Telugu',
    'ta': 'Tamil',
    'mr': 'Marathi',
    'gu': 'Gujarati',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'pa': 'Punjabi',
    'or': 'Odia',
    'as': 'Assamese',
    'mai': 'Maithili',
    'sat': 'Santali',
    'ks': 'Kashmiri',
    'sd': 'Sindhi',
    'ne': 'Nepali',
    'doi': 'Dogri',
    'mni': 'Manipuri',
    'bodo': 'Bodo',
    # Special
    'hinglish': 'Hinglish',
    # Major world languages
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'zh': 'Chinese',
    'ja': 'Japanese',
    'ko': 'Korean',
    'ru': 'Russian',
    'ar': 'Arabic',
    'pt': 'Portuguese',
    'it': 'Italian',
    'nl': 'Dutch',
    'pl': 'Polish',
    'tr': 'Turkish',
    'vi': 'Vietnamese',
    'th': 'Thai',
    'id': 'Indonesian',
    'ms': 'Malay',
    'fa': 'Persian',
    'sw': 'Swahili',
    'tl': 'Tagalog',
    'el': 'Greek',
    'he': 'Hebrew',
    'ro': 'Romanian',
    'hu': 'Hungarian',
    'cs': 'Czech',
    'sv': 'Swedish',
    'fi': 'Finnish',
    'da': 'Danish',
    'no': 'Norwegian',
    'uk': 'Ukrainian',
    'bg': 'Bulgarian',
    'sr': 'Serbian',
    'hr': 'Croatian',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'et': 'Estonian',
    'ca': 'Catalan',
    'gl': 'Galician',
    'eu': 'Basque',
    'af': 'Afrikaans',
    'is': 'Icelandic',
    'mt': 'Maltese',
    'sq': 'Albanian',
    'mk': 'Macedonian',
    'bs': 'Bosnian',
    'mn': 'Mongolian',
    'km': 'Khmer',
    'lo': 'Lao',
    'my': 'Burmese',
    'si': 'Sinhala',
    'am': 'Amharic',
    'hy': 'Armenian',
    'ka': 'Georgian',
    'az': 'Azerbaijani',
    'uz': 'Uzbek',
    'kk': 'Kazakh',
    'ky': 'Kyrgyz',
    'tg': 'Tajik',
    'tk': 'Turkmen',
    'ps': 'Pashto',
    'dv': 'Divehi',
    'dz': 'Dzongkha',
    'bh': 'Bihari',
    'br': 'Breton',
    'cy': 'Welsh',
    'ga': 'Irish',
    'gd': 'Scottish Gaelic',
    'gv': 'Manx',
    'kw': 'Cornish',
    'lb': 'Luxembourgish',
    'li': 'Limburgish',
    'nds': 'Low German',
    'oc': 'Occitan',
    'rm': 'Romansh',
    'sc': 'Sardinian',
    'se': 'Northern Sami',
    'sma': 'Southern Sami',
    'smj': 'Lule Sami',
    'smn': 'Inari Sami',
    'sms': 'Skolt Sami',
    'yi': 'Yiddish',
    'jv': 'Javanese',
    'su': 'Sundanese',
    'ceb': 'Cebuano',
    'hmn': 'Hmong',
    'ht': 'Haitian Creole',
    'ny': 'Chichewa',
    'sn': 'Shona',
    'st': 'Sesotho',
    'tn': 'Setswana',
    'ts': 'Tsonga',
    've': 'Venda',
    'xh': 'Xhosa',
    'zu': 'Zulu',
    'rw': 'Kinyarwanda',
    'rn': 'Kirundi',
    'mg': 'Malagasy',
    'eo': 'Esperanto',
    'la': 'Latin',
    # Add more as needed
}

# ----------------------------------------------------------------------
# Language code normalisation (e.g., "hin" -> "hi")
# ----------------------------------------------------------------------
CODE_VARIATIONS = {
    'hin': 'hi',
    'eng': 'en',
    'urd': 'ur',
    'ben': 'bn',
    'tel': 'te',
    'tam': 'ta',
    'mar': 'mr',
    'guj': 'gu',
    'kan': 'kn',
    'mal': 'ml',
    'pan': 'pa',
    'ori': 'or',
    'asm': 'as',
    'nep': 'ne',
    'spa': 'es',
    'fre': 'fr',
    'fra': 'fr',
    'ger': 'de',
    'deu': 'de',
    'chi': 'zh',
    'zho': 'zh',
    'jpn': 'ja',
    'kor': 'ko',
    'rus': 'ru',
    'ara': 'ar',
    'por': 'pt',
    'ita': 'it',
    'dut': 'nl',
    'nld': 'nl',
    'pol': 'pl',
    'tur': 'tr',
    'vie': 'vi',
    'tha': 'th',
    'ind': 'id',
    'may': 'ms',
    'msa': 'ms',
    'per': 'fa',
    'fas': 'fa',
    'swa': 'sw',
    'tgl': 'tl',
    'gre': 'el',
    'ell': 'el',
    'heb': 'he',
    'rum': 'ro',
    'ron': 'ro',
    'hun': 'hu',
    'cze': 'cs',
    'ces': 'cs',
    'swe': 'sv',
    'fin': 'fi',
    'dan': 'da',
    'nor': 'no',
    'ukr': 'uk',
    'bul': 'bg',
    'srp': 'sr',
    'hrv': 'hr',
    'slk': 'sk',
    'slv': 'sl',
    'lit': 'lt',
    'lav': 'lv',
    'est': 'et',
    'cat': 'ca',
    'glg': 'gl',
    'eus': 'eu',
    'baq': 'eu',
    'afr': 'af',
    'isl': 'is',
    'ice': 'is',
    'mlt': 'mt',
    'sqi': 'sq',
    'alb': 'sq',
    'mkd': 'mk',
    'mac': 'mk',
    'bos': 'bs',
    'mon': 'mn',
    'khm': 'km',
    'lao': 'lo',
    'bur': 'my',
    'mya': 'my',
    'sin': 'si',
    'amh': 'am',
    'hye': 'hy',
    'arm': 'hy',
    'kat': 'ka',
    'geo': 'ka',
    'aze': 'az',
    'uzb': 'uz',
    'kaz': 'kk',
    'kir': 'ky',
    'tgk': 'tg',
    'tuk': 'tk',
    'pus': 'ps',
    'div': 'dv',
    'dzo': 'dz',
    'bih': 'bh',
    'bre': 'br',
    'cym': 'cy',
    'wel': 'cy',
    'gle': 'ga',
    'gla': 'gd',
    'glv': 'gv',
    'cor': 'kw',
    'ltz': 'lb',
    'lim': 'li',
    'nds': 'nds',
    'oci': 'oc',
    'roh': 'rm',
    'srd': 'sc',
    'sme': 'se',
    'sma': 'sma',
    'smj': 'smj',
    'smn': 'smn',
    'sms': 'sms',
    'yid': 'yi',
    'jav': 'jv',
    'sun': 'su',
    'ceb': 'ceb',
    'hmn': 'hmn',
    'hat': 'ht',
    'nya': 'ny',
    'sna': 'sn',
    'sot': 'st',
    'tsn': 'tn',
    'tso': 'ts',
    'ven': 've',
    'xho': 'xh',
    'zul': 'zu',
    'kin': 'rw',
    'run': 'rn',
    'mlg': 'mg',
    'epo': 'eo',
    'lat': 'la',
}

def normalize_language_code(code: str) -> str:
    """
    Convert a language code (e.g., 'hin', 'eng', 'fre') to its ISO 639-1 equivalent.
    If not found, return the original code.
    """
    if not code or not isinstance(code, str):
        return 'en'
    code = code.strip().lower()
    return CODE_VARIATIONS.get(code, code)

# ----------------------------------------------------------------------
# Main function: get human‑readable language name
# ----------------------------------------------------------------------
def get_language_name(code: str) -> str:
    """
    Return the human‑readable name for a language code (ISO 639-1).
    If the code is not found, return the code itself.
    """
    if not code or not isinstance(code, str):
        return 'English'
    code = normalize_language_code(code)
    return LANGUAGE_NAMES.get(code, code)

# ----------------------------------------------------------------------
# Exports
# ----------------------------------------------------------------------
__all__ = [
    "get_language_name",
    "normalize_language_code",
]
